### ISSUE TITLE
Success, but no output files

### ISSUE THREAD

**Issue by RCH-9** [hubblec4/hSplit#1]
Even using the most simple argument of "hsplit file" it outputs nothing at all apart from Exit code 0.

Tried different arguments, different files, and different OS's, all the same result. It even comes up with a success message if I intentionally put wrong commands in, such as a non-existent input file.

**Comment by hubblec4** [comment]
Hi RCH-9
Sorry for this long delay.

Exists the root parameter file "params.txt" in hsplit folder?
If not, please create a blank params.txt file.

It's been a long time since I've written this tool, but I think there was a problem with this parameter file.

**Comment by hubblec4** [comment]
fixed https://github.com/hubblec4/hSplit/commit/b97fcd1d375f9248a0ba028e0a173384ef9422c3

**Comment by RCH-9** [comment]
Tried the update and it now works fine, thanks for the fix.
